Importing Libraries

In [2]:
import numpy as np
import pandas as pd
import ast

Importing Dataset

In [3]:
movies=pd.read_csv('tmdb_5000_movies.csv')
credits=pd.read_csv('tmdb_5000_credits.csv')

In [4]:
movies.head()
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

Merging and sorting dataset

In [7]:
movies=movies.merge(credits, on='title')
movies=movies[['movie_id', 'title', 'overview', 'genres', 'keywords', 'cast', 'crew']]
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

Pre-processing data

In [9]:
def convert(obj):
    L=[]
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [10]:
movies['genres']=movies['genres'].apply(convert)
movies['keywords']=movies['keywords'].apply(convert)

In [12]:
def convert3(obj):
    L=[]
    for i in ast.literal_eval(obj):
        if counter!=3:
            L.append(i['name'])
            counter+=1
        else:
            break
    return L

In [15]:
movies['cast']=movies['cast'].apply(convert3)
movies.head()

UnboundLocalError: local variable 'counter' referenced before assignment

In [16]:
movies['overview'] = movies['overview'].apply(lambda x:str(x).split())
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [17]:
def fetch_director(obj):
    L = []
    for i in ast.literal_eval(obj):
        if i['job'] == 'Director':
            L.append(i['name'])
            break
    return L

In [18]:
movies['crew'] = movies['crew'].apply(fetch_director)
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...",[Andrew Stanton]

In [19]:
movies['genres'] = movies['genres'].apply(lambda x:[i.replace(" "," ") for i in x])
movies['keywords'] = movies['keywords'].apply(lambda x:[i.replace(" "," ") for i in x])
movies['cast'] = movies['cast'].apply(lambda x:[i.replace(" "," ") for i in x])
movies['crew'] = movies['crew'].apply(lambda x:[i.replace(" "," ") for i in x])

In [20]:

movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[[, {, "", c, a, s, t, _, i, d, "", :, , 2, 4, ...",[James Cameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[[, {, "", c, a, s, t, _, i, d, "", :, , 4, ,, ...",[Gore Verbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[[, {, "", c, a, s, t, _, i, d, "", :, , 1, ,, ...",[Sam Mendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[[, {, "", c, a, s, t, _, i, d, "", :, , 2, ,, ...",[Christopher Nolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[[, {, "", c, a, s, t, _, i, d, "", :, , 5, ,, ...",[Andrew Stanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [21]:
new_df = movies[['movie_id','title','tags']]
new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))
new_df.head()

C:\Users\Aryan\AppData\Local\Temp\ipykernel_24572\3819278679.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

Importing NLTK

In [23]:
import nltk
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [24]:
def stem(text):
    y=[]
    
    for i in text.split():
        y.append(ps.stem(i))
        
    return " ".join(y)

In [27]:
new_df['tags'] = new_df['tags'].apply(stem)

C:\Users\Aryan\AppData\Local\Temp\ipykernel_24572\3213734980.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)

In [28]:
new_df['tags']=new_df['tags'].apply(lambda x:x.lower())
new_df.head()

C:\Users\Aryan\AppData\Local\Temp\ipykernel_24572\3109534624.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believ to be dead, ha c..."
2,206647,Spectre,a cryptic messag from bond’ past send him on a...
3,49026,The Dark Knight Rises,follow the death of district attorney harvey d...
4,49529,John Carter,"john carter is a war-weary, former militari ca..."

Importing CountVectorizer

In [30]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

In [31]:
vector = cv.fit_transform(new_df['tags']).toarray()
vector

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [32]:
cv.get_feature_names()

c:\Users\Aryan\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

['000',
 '007',
 '10',
 '100',
 '11',
 '12',
 '13',
 '14',
 '15',
 '150',
 '15th',
 '16',
 '16th',
 '17',
 '17th',
 '18',
 '1890',
 '18th',
 '19',
 '1910',
 '1920',
 '1930',
 '1940',
 '1944',
 '1950',
 '1950s',
 '1955',
 '1959',
 '1960',
 '1960s',
 '1962',
 '1964',
 '1965',
 '1967',
 '1970',
 '1970s',
 '1971',
 '1972',
 '1973',
 '1974',
 '1976',
 '1979',
 '1980',
 '1980s',
 '1985',
 '1990',
 '1995',
 '1997',
 '1999',
 '19th',
 '20',
 '200',
 '2000',
 '2001',
 '2002',
 '2003',
 '2009',
 '20th',
 '21st',
 '23',
 '24',
 '25',
 '30',
 '300',
 '3d',
 '40',
 '50',
 '500',
 '51',
 '60',
 '60s',
 '66',
 '70',
 '80',
 'aaron',
 'abandon',
 'abbi',
 'abduct',
 'abil',
 'abl',
 'aboard',
 'aborigin',
 'abov',
 'abraham',
 'abroad',
 'absolut',
 'absurd',
 'abu',
 'academ',
 'academi',
 'academy',
 'accent',
 'accept',
 'access',
 'accid',
 'accident',
 'acclaim',
 'accompani',
 'accomplish',
 'account',
 'accu',
 'ace',
 'achiev',
 'acquaint',
 'acquir',
 'act',
 'action',
 'activ',
 'activist',
 'activities',
 'actor',
 'actress',
 'actual',
 'ad',
 'adam',
 'adapt',
 'add',
 'addict',
 'adjust',
 'admir',
 'admit',
 'adolesc',
 'adolf',
 'adopt',
 'ador',
 'adrian',
 'adult',
 'adulteri',
 'adulthood',
 'advanc',
 'adventur',
 'adventure',
 'adventures',
 'adverti',
 'advi',
 'advic',
 'affair',
 'affect',
 'afghanistan',
 'africa',
 'african',
 'aftercreditsst',
 'afterlif',
 'aftermath',
 'ag',
 'age',
 'agenc',
 'agency',
 'agenda',
 'agent',
 'agents',
 'aggress',
 'ago',
 'agr',
 'ahead',
 'aid',
 'ail',
 'aim',
 'air',
 'aircraft',
 'airplan',
 'airport',
 'aka',
 'al',
 'alabama',
 'alan',
 'alarm',
 'alaska',
 'alaskan',
 'albert',
 'alcatraz',
 'alcohol',
 'alejandro',
 'alex',
 'alexand',
 'alfr',
 'ali',
 'alic',
 'alice',
 'alien',
 'aliens',
 'alik',
 'aliv',
 'alive',
 'allen',
 'alli',
 'allianc',
 'allow',
 'alon',
 'alongsid',
 'alpha',
 'alreadi',
 'alter',
 'altern',
 'alway',
 'alyssa',
 'alzheimer',
 'amanda',
 'amateur',
 'amaz',
 'amazon',
 'ambassador',
 'ambigu',
 'ambit',
 'ambiti',
 'ambul',
 'ambush',
 'america',
 'american',
 'ami',
 'amid',
 'amidst',
 'amnesia',
 'amp',
 'amsterdam',
 'amu',
 'amy',
 'ana',
 'anakin',
 'analyst',
 'anarch',
 'ancient',
 'anderson',
 'andi',
 'andrew',
 'android',
 'andy',
 'ang',
 'angel',
 'angela',
 'angeles',
 'anger',
 'angri',
 'angst',
 'ani',
 'anim',
 'animals',
 'ann',
 'anna',
 'annabel',
 'anni',
 'annie',
 'anniversari',
 'announc',
 'annual',
 'anonym',
 'anoth',
 'answer',
 'ant',
 'antholog',
 'anthoni',
 'anthropomorph',
 'anti',
 'antic',
 'antiqu',
 'antoin',
 'anton',
 'antonio',
 'anyon',
 'anyth',
 'apart',
 'apartheid',
 'apartment',
 'ape',
 'apocalyp',
 'apocalypse',
 'apocalypt',
 'appar',
 'appear',
 'appl',
 'apple',
 'appli',
 'appoint',
 'appreci',
 'apprehend',
 'apprent',
 'approach',
 'approaches',
 'april',
 'aquarium',
 'arab',
 'arbitrari',
 'arch',
 'archaeologist',
 'archeolog',
 'archer',
 'architect',
 'arctic',
 'area',
 'aren',
 'arena',
 'argument',
 'ari',
 'aristocrat',
 'arizona',
 'ark',
 'arm',
 'armi',
 'armor',
 'armstrong',
 'army',
 'arnold',
 'aronofski',
 'arrang',
 'array',
 'arrest',
 'arriv',
 'arrives',
 'arrog',
 'arrow',
 'arson',
 'art',
 'arthur',
 'articl',
 'artifact',
 'artifici',
 'artist',
 'artists',
 'ash',
 'ashley',
 'asia',
 'asian',
 'asid',
 'ask',
 'aspect',
 'aspir',
 'assassin',
 'assault',
 'assembl',
 'assign',
 'assignment',
 'assist',
 'assistant',
 'associ',
 'assum',
 'asteroid',
 'astronaut',
 'asylum',
 'atheist',
 'athlet',
 'atlant',
 'atlanta',
 'atom',
 'attach',
 'attack',
 'attacks',
 'attempt',
 'attend',
 'attent',
 'attic',
 'attitud',
 'attorney',
 'attract',
 'auction',
 'audienc',
 'audio',
 'audit',
 'august',
 'aunt',
 'austin',
 'australia',
 'australian',
 'austria',
 'author',
 'autism',
 'auto',
 'autobiograph',
 'automobil',
 'avail',
 'aveng',
 'averag',
 'aviat',
 'avoid',
 'await',
 'awak',
 'awaken',
 'awar',
 'award',
 'away',
 'awesom',
 'awkward',
 'awri',
 'awry',
 'ax',
 'axe',
 'ayer',
 'ba',
 'babe',
 'babi',
 'baby',
 'bachelor',
 'backdrop',
 'background',
 'backpack',
 'backyard',
 'bad',
 'bag',
 'bahama',
 'bail',
 'baker',
 'balanc',
 'ball',
 'ballet',
 'balloon',
 'baltimor',
 'ban',
 'band',
 'bandit',
 'bangkok',
 'banish',
 'bank',
 'banker',
 'banner',
 'bar',
 'barbara',
 'barbarian',
 'barcelona',
 'bare',
 'bargain',
 'barn',
 'barney',
 'baron',
 'barri',
 'barrier',
 'barry',
 'bart',
 'base',
 'baseb',
 'basement',
 'basketb',
 'basketball',
 'bat',
 'bath',
 'bathroom',
 'batman',
 'battalion',
 'battl',
 'battle',
 'battlefield',
 'bay',
 'baz',
 'beach',
 'beam',
 'bear',
 'beard',
 'beast',
 'beat',
 'beaten',
 'beauti',
 'beautiful',
 'beauty',
 'becam',
 'becau',
 'becker',
 'becki',
 'becom',
 'bed',
 'bedroom',
 'bee',
 'beer',
 'befor',
 'befriend',
 'beg',
 'began',
 'begin',
 'begins',
 'behavior',
 'behead',
 'belgium',
 'belief',
 'believ',
 'bell',
 'bella',
 'belong',
 'belov',
 'belt',
 'ben',
 'bend',
 'beneath',
 'benefit',
 'benito',
 'benjamin',
 'bennett',
 'bent',
 'berg',
 'berlin',
 'best',
 'bet',
 'beth',
 'betray',
 'betrayal',
 'better',
 'betti',
 'beverli',
 'bibl',
 'biblic',
 'bicycl',
 'bid',
 'big',
 'bigger',
 'biggest',
 'bike',
 'biker',
 'bikini',
 'billi',
 'billion',
 'billionair',
 'biographi',
 'biolog',
 'biologist',
 'bird',
 'birth',
 'birthday',
 'bisexu',
 'bishop',
 'bit',
 'bite',
 'bitten',
 'bitter',
 'bizarr',
 'black',
 'blackmail',
 'blacksmith',
 'blade',
 'blake',
 'blame',
 'blend',
 'bless',
 'blind',
 'bliss',
 'blizzard',
 'block',
 'blond',
 'blood',
 'bloodi',
 'bloodthirsti',
 'blow',
 'blue',
 'board',
 'boat',
 'bob',
 'bobbi',
 'bodi',
 'body',
 'bodyguard',
 'bold',
 'bollywood',
 'bomb',
 'bomber',
 'bond',
 'bone',
 'bong',
 'boobi',
 'book',
 'border',
 'bore',
 'boredom',
 'born',
 'boss',
 'boston',
 'botch',
 'bottl',
 'bound',
 'boundari',
 'bounti',
 'bout',
 'bowl',
 'bowman',
 'box',
 'boxer',
 'boy',
 'boyd',
 'boyfriend',
 'boyl',
 'boys',
 'brad',
 'brain',
 'brainwash',
 'branagh',
 'brand',
 'brandon',
 'brave',
 'braveri',
 'brazil',
 'brazilian',
 'break',
 'breakdown',
 'breakfast',
 'breakup',
 'breast',
 'breath',
 'breed',
 'brent',
 'brett',
 'brian',
 'brick',
 'bride',
 'bridesmaid',
 'bridg',
 'brief',
 'bright',
 'brilliant',
 'bring',
 'brink',
 'britain',
 'british',
 'broadcast',
 'broadway',
 'broke',
 'broken',
 'broker',
 'bronx',
 'brood',
 'brook',
 'brooklyn',
 'broom',
 'brothel',
 'brother',
 'brothers',
 'brought',
 'brown',
 'bruce',
 'brutal',
 'bryan',
 'bu',
 'buck',
 'bud',
 'budapest',
 'buddhist',
 'buddi',
 'buddy',
 'budget',
 'buffalo',
 'build',
 'building',
 'built',
 'bull',
 'bullet',
 'bulli',
 'bum',
 'bumbl',
 'bunch',
 'bunker',
 'bunni',
 'burger',
 'burglar',
 'buri',
 'burn',
 'burton',
 'bush',
 'busi',
 'business',
 'businessman',
 'bust',
 'butch',
 'butcher',
 'butler',
 'butt',
 'button',
 'buy',
 'buzz',
 'cabin',
 'caesar',
 'cage',
 'cain',
 'cairo',
 'cal',
 'caleb',
 'california',
 'calm',
 'calvin',
 'camcord',
 'came',
 'cameo',
 'camera',
 'cameraman',
 'cameron',
 'camp',
 'campaign',
 'campbel',
 'campbell',
 'campu',
 'canada',
 'canadian',
 'cancer',
 'candi',
 'candid',
 'candlelight',
 'canin',
 'cannabi',
 'cannib',
 'cannon',
 'canuxploit',
 'canyon',
 'cap',
 'capabl',
 'cape',
 'caper',
 'capit',
 'capra',
 'capt',
 'captain',
 'captiv',
 'captur',
 'capture',
 'car',
 'card',
 'care',
 'career',
 'carefr',
 'caretak',
 'cargo',
 'caribbean',
 'carl',
 'carlo',
 'carmen',
 'carniv',
 'carol',
 'carolina',
 'carpent',
 'carri',
 'carrier',
 'cartel',
 'carter',
 'cartoon',
 'case',
 'cash',
 'casino',
 'cast',
 'castl',
 'castle',
 'casual',
 'cat',
 'cataclysm',
 'catastroph',
 'catch',
 'catherin',
 'cathol',
 'cattl',
 'cau',
 'caught',
 'cause',
 'cavalri',
 'cave',
 'cavemen',
 'celebr',
 'celebration',
 'cell',
 'cemeteri',
 'center',
 'centr',
 'central',
 'centuri',
 'centuries',
 'century',
 'ceo',
 'ceremoni',
 'certain',
 'chad',
 'chain',
 'chainsaw',
 'chair',
 'challeng',
 'chamber',
 'champion',
 'championship',
 'chan',
 'chanc',
 'chance',
 'chang',
 'change',
 'changed',
 'changes',
 'channel',
 'chao',
 'chaos',
 'chaotic',
 'chapman',
 'chapter',
 'charact',
 'character',
 'characters',
 'charg',
 'charismat',
 'charl',
 'charli',
 'charlie',
 'charlott',
 'charm',
 'chart',
 'chase',
 'chat',
 'chauffeur',
 'cheat',
 'check',
 'cheerlead',
 'chef',
 'chemic',
 'chest',
 'chicago',
 'chicken',
 'chief',
 'child',
 'childhood',
 'children',
 'chill',
 'chimp',
 'china',
 'chine',
 'chip',
 'chipmunk',
 'chloe',
 'chocol',
 'choic',
 'choice',
 'choir',
 'chon',
 'choo',
 'chopra',
 'choru',
 'chosen',
 'chri',
 'christ',
 'christian',
 'christin',
 'christma',
 'christmas',
 'christoph',
 'chronicl',
 'chuck',
 'church',
 'cia',
 'cigar',
 'cigarett',
 'cinderella',
 'cindi',
 'cinema',
 'cinemat',
 'circl',
 'circle',
 'circu',
 'circuit',
 'circumst',
 'circumstances',
 'citi',
 'citizen',
 'city',
 'civil',
 'civilian',
 'civilization',
 'claim',
 'clair',
 'clan',
 'clark',
 'clash',
 'class',
 'classic',
 'classmat',
 'classroom',
 'clau',
 'claud',
 'claudia',
 'claustrophobia',
 'clay',
 'clean',
 'clear',
 'clerk',
 'clever',
 'client',
 'clients',
 'cliff',
 'climat',
 'climb',
 'climber',
 'clinic',
 'clint',
 'clock',
 'clone',
 'clooney',
 'close',
 'closer',
 'closet',
 'cloud',
 'clown',
 'club',
 'clue',
 'clueless',
 'clumsi',
 'clutch',
 'coach',
 'coal',
 'coast',
 'cocain',
 'code',
 'codi',
 'coen',
 'coffin',
 'cohen',
 'col',
 'cold',
 'cole',
 'colin',
 'collap',
 'collar',
 'colleagu',
 'collect',
 'collector',
 'colleg',
 'college',
 'collet',
 'colli',
 'collid',
 'collin',
 'colombia',
 'colonel',
 'coloni',
 'color',
 'colorado',
 'columbu',
 'coma',
 'combat',
 'combin',
 'come',
 'comeback',
 'comedi',
 'comedian',
 'comedy',
 'comet',
 'comfort',
 'comic',
 'coming',
 'command',
 'commando',
 'commerci',
 'commiss',
 'commit',
 'common',
 'commun',
 'communist',
 'community',
 'compani',
 'companion',
 'company',
 'compass',
 'compet',
 'competit',
 'competition',
 'complet',
 'complex',
 'complic',
 'compo',
 'compul',
 'comput',
 'conan',
 'concentr',
 'concern',
 'concert',
 'concoct',
 'condit',
 'conduct',
 'confed',
 'confer',
 'confess',
 'confid',
 'confin',
 'conflict',
 'confront',
 'confu',
 'congress',
 'connect',
 'connecticut',
 'conni',
 'connor',
 'conquer',
 'conrad',
 'conscienc',
 'consequ',
 'consequences',
 'conserv',
 'consid',
 'conspir',
 'conspiraci',
 'conspiracy',
 'constant',
 'constantli',
 'construct',
 'consum',
 'contact',
 'contain',
 'contemporari',
 'contend',
 'content',
 'contest',
 'contin',
 'continu',
 'contract',
 'contractor',
 'control',
 'controversi',
 'conveni',
 ...]

In [33]:
from sklearn.metrics.pairwise import cosine_similarity

In [34]:
similarity = cosine_similarity(vector)

In [35]:
def recommend(movie):
    movie_index = new_df[new_df['title'] == movie].index[0]
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]


    for i in movies_list:
        print(new_df.iloc[i[0]].title)

In [36]:
recommend('The Godfather')

The Godfather: Part II
10th & Wolf
Blood Ties
Easy Money
Batman Begins

In [37]:
import pickle

In [38]:
pickle.dump(new_df.to_dict(),open('movies_dict.pkl','wb'))
pickle.dump(similarity,open('similarity.pkl','wb'))